apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: backend-reminder-cron-subscription
  namespace: todo-app
spec:
  topic: reminder-cron-topic
  route: /api/reminders/cron-handler
  pubsubname: kafka-pubsub
  metadata:
    rawPayload: "false"
  scopes:
  - backend