apiVersion: v1
kind: Service
metadata:
  name: recurring-task-service
  namespace: todo-app
  labels:
    app: recurring-task-service
spec:
  selector:
    app: recurring-task-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP